version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # ofelia:
  #   image: mcuadros/ofelia:latest
  #   depends_on:
  #     - nginx
  #   command: daemon --docker
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   labels:
  #     ofelia.job-local.my-test-job.schedule: "@every 5s"
  #     ofelia.job-local.my-test-job.command: "date"
  # stakeboard:
  #   build: .
  #   ports:
  #     - "80:3000"
