version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # sync-scheduler:
  #   build: 
  #     context: ./sync-scheduler
  # stakeboard:
  #   build: .
  #   ports:
  #     - "3000:3000"
    
