version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  syncer:
    image: lukmyslinski/dumbcron:v1.0.1
    environment:
      TARGET_URL: "http://stakeboard:3000/api/sync"      
      SLEEP_DURATION: 3600
      INITIAL_DELAY: 30
    restart: always
  stakeboard:
    image: lukmyslinski/stakeboard:v1.0.0
    ports:
      - "80:3000"
    restart: always