version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # syncer:
  #   image: lukmyslinski/dumbcron:1.0.0
  #   environment:
  #     TARGET_URL: "http://stakeboard:3000/api/sync"      
  #     SLEEP_DURATION: 3600
  #     INITIAL_DELAY: 30
  #   restart: always
  # stakeboard:
  #   build: .
  #   image: lukmyslinski/stakeboard
  #   ports:
  #     - "3000:3000"
  #   restart: always
    
