version: "3.2"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  syncer:
    build: 
      context: ./syncer
    environment:
      STAKEBOARD_HOST: "http://stakeboard:3000"      
      SLEEP_DURATION: 3600
    restart: always
  stakeboard:
    build: .
    ports:
      - "3000:3000"
    restart: always
    
